select * from SD18EXAM_tbQuizVersion
select * from [dbo].[SD18EXAM_tbXMLQuizContent]
select * from [dbo].[SD18EXAM_tbCourse]
select * from [dbo].[SD18EXAM_tbUser]
select * from [dbo].[SD18EXAM_tbClass]
select * from SD18EXAM_tbIssuedQuiz
select * from SD18EXAM_tbToken
select * from [dbo].[SD18EXAM_tbQuizStudent]
select * from [dbo].[SD18EXAM_tbQuizStudentStatus]
select * from [dbo].[SD18EXAM_tbQuizStatus]
